### PR TITLE
Update my current location.

### PR DESCRIPTION
**Pull request by craigbox**

### CODE REVIEW

**Comment by craigbox** [comment]
*bump* and this one

**Comment by chris-short** [comment]
Can you add on as opposed to replacing?

**Comment by craigbox** [comment]
I'm happy as-is; the new hosts can update for their podcast if they wish.

**Comment by craigbox** [comment]
_bump_ again.

**Comment by chris-short** [comment]
> I'm happy as-is; the new hosts can update for their podcast if they wish.

Well, I'm not happy as-is.

**Pull request closed without merging**
